import { requireUser } from './_lib/session.js';
import { supabase } from './_lib/db.js';

function text(v,max=200){return v==null?'':String(v).trim().slice(0,max)}
function dayIndex(dateStr,timeZone){const d=new Date(`${dateStr}T12:00:00Z`);const wd=new Intl.DateTimeFormat('en-US',{timeZone,weekday:'short'}).format(d);return['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(wd)}
function addDay(dateStr){const d=new Date(`${dateStr}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10)}
function zonedDate(dateStr,timeStr,timeZone){const [y,m,d]=dateStr.split('-').map(Number),[hh,mm]=timeStr.slice(0,5).split(':').map(Number);let ts=Date.UTC(y,m-1,d,hh,mm,0);for(let i=0;i<2;i++){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ts)).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));const seen=Date.UTC(+parts.year,+parts.month-1,+parts.day,+parts.hour,+parts.minute,+parts.second);ts-=(seen-Date.UTC(y,m-1,d,hh,mm,0))}return new Date(ts)}
function mins(t){const [h,m]=String(t).slice(0,5).split(':').map(Number);return h*60+m}function hhmm(n){return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
async function doctorForUser(userId){const {data}=await supabase.from('doctor_profiles').select('id,slug,full_name,specialty,city,timezone,verification_status,public_profile').eq('user_id',userId).maybeSingle();return data}

export default async function handler(req,res){
  if(req.method==='GET'){
    if(String(req.query?.mine||'')==='1'){
      const session=requireUser(req,res);if(!session)return;const doctor=await doctorForUser(session.sub);if(!doctor)return res.status(403).json({success:false,error:'پروفایل پزشک پیدا نشد'});
      const {data,error}=await supabase.from('doctor_availability').select('*').eq('doctor_id',doctor.id).order('weekday').order('start_time');if(error)return res.status(500).json({success:false,error:'برنامه دریافت نشد'});return res.status(200).json({success:true,doctor,schedule:data||[]});
    }
    const doctorId=text(req.query?.doctor_id,64),slug=text(req.query?.slug,120),date=text(req.query?.date,10);if(!doctorId&&!slug)return res.status(400).json({success:false,error:'پزشک مشخص نشده است'});
    let q=supabase.from('doctor_profiles').select('id,slug,full_name,specialty,city,timezone,verification_status,public_profile').eq('verification_status','verified').eq('public_profile',true);q=doctorId?q.eq('id',doctorId):q.eq('slug',slug);
    const {data:doctor}=await q.maybeSingle();if(!doctor)return res.status(404).json({success:false,error:'پزشک پیدا نشد'});
    const {data:schedule,error}=await supabase.from('doctor_availability').select('*').eq('doctor_id',doctor.id).eq('active',true).order('weekday').order('start_time');if(error)return res.status(500).json({success:false,error:'برنامه پزشک دریافت نشد'});
    if(!date)return res.status(200).json({success:true,doctor,schedule:schedule||[]});if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return res.status(400).json({success:false,error:'تاریخ معتبر نیست'});
    const weekday=dayIndex(date,doctor.timezone||'Asia/Tehran'),rows=(schedule||[]).filter(x=>Number(x.weekday)===weekday),dayStart=zonedDate(date,'00:00',doctor.timezone||'Asia/Tehran').toISOString(),dayEnd=zonedDate(addDay(date),'00:00',doctor.timezone||'Asia/Tehran').toISOString();
    const {data:appointments}=await supabase.from('appointments').select('starts_at,ends_at,status').eq('doctor_id',doctor.id).gte('starts_at',dayStart).lt('starts_at',dayEnd).neq('status','cancelled');const slots=[];
    for(const r of rows){const start=mins(r.start_time),end=mins(r.end_time),step=Math.max(10,Math.min(180,Number(r.slot_minutes)||30));for(let n=start;n+step<=end;n+=step){const local=hhmm(n),s=zonedDate(date,local,doctor.timezone||'Asia/Tehran'),e=new Date(s.getTime()+step*60000),busy=(appointments||[]).some(a=>{const as=new Date(a.starts_at),ae=a.ends_at?new Date(a.ends_at):new Date(as.getTime()+step*60000);return s<ae&&e>as});if(!busy&&s.getTime()>Date.now()+5*60000)slots.push({starts_at:s.toISOString(),ends_at:e.toISOString(),local_time:local,mode:r.mode,organization_id:r.organization_id,slot_minutes:step})}}
    return res.status(200).json({success:true,doctor,date,slots});
  }
  const session=requireUser(req,res);if(!session)return;const doctor=await doctorForUser(session.sub);if(!doctor)return res.status(403).json({success:false,error:'حساب پزشک پیدا نشد'});const body=req.body&&typeof req.body==='object'?req.body:{};
  if(req.method==='POST'){const weekday=Number(body.weekday),start=text(body.start_time,5),end=text(body.end_time,5),slot=Math.max(10,Math.min(180,Number(body.slot_minutes)||30)),mode=['in_person','video','phone'].includes(body.mode)?body.mode:'in_person';if(!Number.isInteger(weekday)||weekday<0||weekday>6||!/^\d{2}:\d{2}$/.test(start)||!/^\d{2}:\d{2}$/.test(end)||mins(start)>=mins(end))return res.status(400).json({success:false,error:'برنامه زمانی معتبر نیست'});const {data,error}=await supabase.from('doctor_availability').insert({doctor_id:doctor.id,organization_id:body.organization_id||null,weekday,start_time:start,end_time:end,slot_minutes:slot,mode,active:true}).select('*').single();if(error)return res.status(500).json({success:false,error:'برنامه ذخیره نشد'});return res.status(201).json({success:true,item:data})}
  if(req.method==='PATCH'){const id=text(body.id,64);if(!id)return res.status(400).json({success:false,error:'شناسه لازم است'});const patch={};if(body.active!=null)patch.active=Boolean(body.active);if(body.start_time)patch.start_time=text(body.start_time,5);if(body.end_time)patch.end_time=text(body.end_time,5);if(body.slot_minutes)patch.slot_minutes=Math.max(10,Math.min(180,Number(body.slot_minutes)||30));if(body.mode)patch.mode=['in_person','video','phone'].includes(body.mode)?body.mode:'in_person';const {data,error}=await supabase.from('doctor_availability').update(patch).eq('id',id).eq('doctor_id',doctor.id).select('*').maybeSingle();if(error||!data)return res.status(404).json({success:false,error:'برنامه پیدا نشد'});return res.status(200).json({success:true,item:data})}
  if(req.method==='DELETE'){const id=text(body.id,64);const {error}=await supabase.from('doctor_availability').delete().eq('id',id).eq('doctor_id',doctor.id);if(error)return res.status(500).json({success:false,error:'حذف انجام نشد'});return res.status(200).json({success:true})}
  return res.status(405).json({error:'Method not allowed'});
}
