import { requireUser } from './_lib/session.js';
import { supabase } from './_lib/db.js';
import { InputValidationError, numberField, dateField } from './_lib/validate.js';
const TYPE_MAP={condition:'patient_conditions',allergy:'patient_allergies',medication:'patient_medications',vaccination:'patient_vaccinations',vital:'patient_vitals',task:'care_tasks',insurance:'patient_insurances',procedure:'patient_procedures',family_history:'patient_family_history',screening:'preventive_screenings'};
async function ensureOwned(userId,patientId){const {data}=await supabase.from('patients').select('id').eq('id',patientId).eq('owner_user_id',userId).maybeSingle();return Boolean(data)}
function text(v,max=500){return v==null?null:String(v).trim().slice(0,max)}
function put(o,k,v,partial,body){if(!partial||body[k]!==undefined)o[k]=v}
function build(type,body,partial=false){
 const p={};
 if(type==='condition'){put(p,'name',text(body.name,160),partial,body);put(p,'status',['active','resolved','inactive'].includes(body.status)?body.status:'active',partial,body);put(p,'diagnosed_at',dateField(body.diagnosed_at,{label:'تاریخ تشخیص',allowFuture:false}),partial,body);put(p,'notes',text(body.notes,2000),partial,body)}
 else if(type==='allergy'){put(p,'allergen',text(body.allergen,160),partial,body);put(p,'allergy_type',['drug','food','environmental','other'].includes(body.allergy_type)?body.allergy_type:'other',partial,body);put(p,'severity',['mild','moderate','severe','unknown'].includes(body.severity)?body.severity:'unknown',partial,body);put(p,'reaction',text(body.reaction,500),partial,body);put(p,'notes',text(body.notes,1500),partial,body)}
 else if(type==='medication'){put(p,'name',text(body.name,160),partial,body);put(p,'dose',text(body.dose,120),partial,body);put(p,'route',text(body.route,80),partial,body);put(p,'frequency',text(body.frequency,120),partial,body);put(p,'instructions',text(body.instructions,1000),partial,body);put(p,'started_at',dateField(body.started_at,{label:'تاریخ شروع',allowFuture:true}),partial,body);put(p,'ended_at',dateField(body.ended_at,{label:'تاریخ پایان',allowFuture:true}),partial,body);put(p,'status',['active','paused','stopped','completed'].includes(body.status)?body.status:'active',partial,body)}
 else if(type==='vaccination'){put(p,'vaccine_name',text(body.vaccine_name,160),partial,body);put(p,'dose_number',text(body.dose_number,80),partial,body);put(p,'administered_at',dateField(body.administered_at,{label:'تاریخ تزریق',allowFuture:false}),partial,body);put(p,'next_due_at',dateField(body.next_due_at,{label:'موعد دوز بعد',allowFuture:true}),partial,body);put(p,'provider',text(body.provider,160),partial,body);put(p,'notes',text(body.notes,1000),partial,body)}
 else if(type==='vital'){put(p,'measured_at',body.measured_at||new Date().toISOString(),partial,body);put(p,'weight_kg',numberField(body.weight_kg,{label:'وزن',min:.2,max:500}),partial,body);put(p,'systolic',numberField(body.systolic,{label:'فشار سیستول',min:20,max:350,integer:true}),partial,body);put(p,'diastolic',numberField(body.diastolic,{label:'فشار دیاستول',min:10,max:250,integer:true}),partial,body);put(p,'heart_rate',numberField(body.heart_rate,{label:'ضربان قلب',min:1,max:350,integer:true}),partial,body);put(p,'oxygen_saturation',numberField(body.oxygen_saturation,{label:'اشباع اکسیژن',min:1,max:100}),partial,body);put(p,'temperature_c',numberField(body.temperature_c,{label:'دما',min:20,max:50}),partial,body);put(p,'glucose_mg_dl',numberField(body.glucose_mg_dl,{label:'قند خون',min:1,max:1500}),partial,body);p.source='manual';put(p,'notes',text(body.notes,500),partial,body)}
 else if(type==='task'){put(p,'type',['medication','lab','appointment','measurement','follow_up','vaccine','general'].includes(body.task_type)?body.task_type:'general',partial,body);put(p,'title',text(body.title,180),partial,body);put(p,'details',text(body.details,1500),partial,body);put(p,'due_at',body.due_at||null,partial,body);put(p,'recurrence_rule',text(body.recurrence_rule,300),partial,body);put(p,'status',['open','completed','cancelled'].includes(body.status)?body.status:'open',partial,body);if(!partial||body.status!==undefined)p.completed_at=body.status==='completed'?new Date().toISOString():null}
 else if(type==='insurance'){put(p,'provider_name',text(body.provider_name,160),partial,body);put(p,'policy_number',text(body.policy_number,120),partial,body);put(p,'plan_name',text(body.plan_name,120),partial,body);put(p,'valid_from',dateField(body.valid_from,{label:'شروع اعتبار',allowFuture:true}),partial,body);put(p,'valid_until',dateField(body.valid_until,{label:'پایان اعتبار',allowFuture:true}),partial,body);put(p,'is_primary',body.is_primary!==false,partial,body)}
 else if(type==='procedure'){put(p,'name',text(body.name,180),partial,body);put(p,'procedure_type',['surgery','procedure','hospitalization','dental','other'].includes(body.procedure_type)?body.procedure_type:'procedure',partial,body);put(p,'performed_at',dateField(body.performed_at,{label:'تاریخ اقدام',allowFuture:false}),partial,body);put(p,'outcome',text(body.outcome,1000),partial,body);put(p,'notes',text(body.notes,2000),partial,body)}
 else if(type==='family_history'){put(p,'relation',text(body.relation,100),partial,body);put(p,'condition_name',text(body.condition_name,180),partial,body);put(p,'age_at_diagnosis',numberField(body.age_at_diagnosis,{label:'سن تشخیص',min:0,max:125,integer:true}),partial,body);put(p,'notes',text(body.notes,1500),partial,body)}
 else if(type==='screening'){put(p,'screening_name',text(body.screening_name,180),partial,body);put(p,'performed_at',dateField(body.performed_at,{label:'تاریخ غربالگری',allowFuture:false}),partial,body);put(p,'next_due_at',dateField(body.next_due_at,{label:'موعد بعدی',allowFuture:true}),partial,body);put(p,'result_summary',text(body.result_summary,1500),partial,body);put(p,'status',['due','scheduled','completed','not_applicable'].includes(body.status)?body.status:'due',partial,body)}
 else return null;return p;
}
function requiredValue(type,p){if(type==='condition'||type==='medication'||type==='procedure')return p.name;if(type==='allergy')return p.allergen;if(type==='vaccination')return p.vaccine_name;if(type==='task')return p.title;if(type==='insurance')return p.provider_name;if(type==='family_history')return p.relation&&p.condition_name;if(type==='screening')return p.screening_name;return true}
export default async function handler(req,res){
 const session=requireUser(req,res);if(!session)return;if(!['POST','PATCH','DELETE'].includes(req.method))return res.status(405).json({error:'Method not allowed'});
 const body=req.body&&typeof req.body==='object'?req.body:{},type=String(body.type||''),table=TYPE_MAP[type],patientId=String(body.patient_id||'');
 if(!table||!patientId||!(await ensureOwned(session.sub,patientId)))return res.status(400).json({success:false,error:'درخواست معتبر نیست'});
 try{
  if(req.method==='POST'){const payload=build(type,body,false);if(!payload)return res.status(400).json({success:false,error:'نوع اطلاعات پشتیبانی نمی‌شود'});if(!requiredValue(type,payload))return res.status(400).json({success:false,error:'اطلاعات ضروری کامل نیست'});const {data,error}=await supabase.from(table).insert({patient_id:patientId,...payload}).select('*').single();if(error)throw error;await supabase.from('audit_logs').insert({actor_user_id:session.sub,actor_type:'user',patient_id:patientId,action:`record.${type}.created`,resource_type:type,resource_id:data.id}).catch(()=>null);return res.status(201).json({success:true,item:data})}
  const id=String(body.id||'');if(!id)return res.status(400).json({success:false,error:'شناسه لازم است'});const {data:existing}=await supabase.from(table).select('id').eq('id',id).eq('patient_id',patientId).maybeSingle();if(!existing)return res.status(404).json({success:false,error:'آیتم پیدا نشد'});
  if(req.method==='DELETE'){const {error}=await supabase.from(table).delete().eq('id',id).eq('patient_id',patientId);if(error)throw error;return res.status(200).json({success:true})}
  const payload=build(type,body,true);if(!payload||!Object.keys(payload).length)return res.status(400).json({success:false,error:'فیلدی برای ویرایش ارسال نشده است'});const {data,error}=await supabase.from(table).update(payload).eq('id',id).eq('patient_id',patientId).select('*').single();if(error)throw error;return res.status(200).json({success:true,item:data});
 }catch(error){if(error instanceof InputValidationError)return res.status(400).json({success:false,error:error.message});console.error('health-entry',error);return res.status(500).json({success:false,error:'ثبت اطلاعات سلامت انجام نشد'})}
}
