import {InputValidationError,numberField,dateField,timestampField} from './validate.js';
function text(v,max=500){return v==null?null:String(v).trim().slice(0,max)}
function put(o,k,v,partial,body,source=k){if(!partial||body[source]!==undefined)o[k]=v}
export function build(type,body,partial=false){
 const p={};
 if(type==='condition'){put(p,'name',text(body.name,160),partial,body);put(p,'status',['active','resolved','inactive'].includes(body.status)?body.status:'active',partial,body);put(p,'diagnosed_at',dateField(body.diagnosed_at,{label:'تاریخ تشخیص',allowFuture:false}),partial,body);put(p,'notes',text(body.notes,2000),partial,body)}
 else if(type==='allergy'){put(p,'allergen',text(body.allergen,160),partial,body);put(p,'allergy_type',['drug','food','environmental','other'].includes(body.allergy_type)?body.allergy_type:'other',partial,body);put(p,'severity',['mild','moderate','severe','unknown'].includes(body.severity)?body.severity:'unknown',partial,body);put(p,'reaction',text(body.reaction,500),partial,body);put(p,'notes',text(body.notes,1500),partial,body)}
 else if(type==='medication'){put(p,'name',text(body.name,160),partial,body);put(p,'dose',text(body.dose,120),partial,body);put(p,'route',text(body.route,80),partial,body);put(p,'frequency',text(body.frequency,120),partial,body);put(p,'instructions',text(body.instructions,1000),partial,body);put(p,'started_at',dateField(body.started_at,{label:'تاریخ شروع',allowFuture:true}),partial,body);put(p,'ended_at',dateField(body.ended_at,{label:'تاریخ پایان',allowFuture:true}),partial,body);put(p,'status',['active','paused','stopped','completed'].includes(body.status)?body.status:'active',partial,body)}
 else if(type==='vaccination'){put(p,'vaccine_name',text(body.vaccine_name,160),partial,body);put(p,'dose_number',text(body.dose_number,80),partial,body);put(p,'administered_at',dateField(body.administered_at,{label:'تاریخ تزریق',allowFuture:false}),partial,body);put(p,'next_due_at',dateField(body.next_due_at,{label:'موعد دوز بعد',allowFuture:true}),partial,body);put(p,'provider',text(body.provider,160),partial,body);put(p,'notes',text(body.notes,1000),partial,body)}
 else if(type==='vital'){put(p,'measured_at',timestampField(body.measured_at,{label:'زمان اندازه‌گیری',allowFuture:false})||new Date().toISOString(),partial,body);put(p,'weight_kg',numberField(body.weight_kg,{label:'وزن',min:.2,max:500}),partial,body);put(p,'systolic',numberField(body.systolic,{label:'فشار سیستول',min:20,max:350,integer:true}),partial,body);put(p,'diastolic',numberField(body.diastolic,{label:'فشار دیاستول',min:10,max:250,integer:true}),partial,body);put(p,'heart_rate',numberField(body.heart_rate,{label:'ضربان قلب',min:1,max:350,integer:true}),partial,body);put(p,'oxygen_saturation',numberField(body.oxygen_saturation,{label:'اشباع اکسیژن',min:1,max:100}),partial,body);put(p,'temperature_c',numberField(body.temperature_c,{label:'دما',min:20,max:50}),partial,body);put(p,'glucose_mg_dl',numberField(body.glucose_mg_dl,{label:'قند خون',min:1,max:1500}),partial,body);if(!partial)p.source='manual';put(p,'notes',text(body.notes,500),partial,body)}
 else if(type==='task'){put(p,'type',['medication','lab','appointment','measurement','follow_up','vaccine','general'].includes(body.task_type)?body.task_type:'general',partial,body,'task_type');put(p,'title',text(body.title,180),partial,body);put(p,'details',text(body.details,1500),partial,body);put(p,'due_at',timestampField(body.due_at,{label:'موعد پیگیری'}),partial,body);put(p,'recurrence_rule',text(body.recurrence_rule,300),partial,body);put(p,'status',['open','completed','cancelled'].includes(body.status)?body.status:'open',partial,body);if(!partial||body.status!==undefined)p.completed_at=body.status==='completed'?new Date().toISOString():null}
 else if(type==='insurance'){put(p,'provider_name',text(body.provider_name,160),partial,body);put(p,'policy_number',text(body.policy_number,120),partial,body);put(p,'plan_name',text(body.plan_name,120),partial,body);put(p,'valid_from',dateField(body.valid_from,{label:'شروع اعتبار',allowFuture:true}),partial,body);put(p,'valid_until',dateField(body.valid_until,{label:'پایان اعتبار',allowFuture:true}),partial,body);put(p,'is_primary',body.is_primary!==false,partial,body)}
 else if(type==='procedure'){put(p,'name',text(body.name,180),partial,body);put(p,'procedure_type',['surgery','procedure','hospitalization','dental','other'].includes(body.procedure_type)?body.procedure_type:'procedure',partial,body);put(p,'performed_at',dateField(body.performed_at,{label:'تاریخ اقدام',allowFuture:false}),partial,body);put(p,'outcome',text(body.outcome,1000),partial,body);put(p,'notes',text(body.notes,2000),partial,body)}
 else if(type==='family_history'){put(p,'relation',text(body.relation,100),partial,body);put(p,'condition_name',text(body.condition_name,180),partial,body);put(p,'age_at_diagnosis',numberField(body.age_at_diagnosis,{label:'سن تشخیص',min:0,max:125,integer:true}),partial,body);put(p,'notes',text(body.notes,1500),partial,body)}
 else if(type==='screening'){put(p,'screening_name',text(body.screening_name,180),partial,body);put(p,'performed_at',dateField(body.performed_at,{label:'تاریخ غربالگری',allowFuture:false}),partial,body);put(p,'next_due_at',dateField(body.next_due_at,{label:'موعد بعدی',allowFuture:true}),partial,body);put(p,'result_summary',text(body.result_summary,1500),partial,body);put(p,'status',['due','scheduled','completed','not_applicable'].includes(body.status)?body.status:'due',partial,body)}
 else return null;
 const mandatory={condition:['name'],medication:['name'],procedure:['name'],allergy:['allergen'],vaccination:['vaccine_name'],task:['title'],insurance:['provider_name'],family_history:['relation','condition_name'],screening:['screening_name']}[type]||[];
 for(const key of mandatory)if(Object.hasOwn(p,key)&&!p[key])throw new InputValidationError('اطلاعات ضروری کامل نیست');
 if(type==='vital'){
  const measures=['weight_kg','systolic','diastolic','heart_rate','oxygen_saturation','temperature_c','glucose_mg_dl'];
  if(!partial&&!measures.some(k=>p[k]!=null))throw new InputValidationError('حداقل یک مقدار علائم حیاتی وارد کنید');
  if(p.systolic!=null&&p.diastolic!=null&&p.systolic<=p.diastolic)throw new InputValidationError('فشار سیستول باید از دیاستول بیشتر باشد');
 }
 for(const [start,end] of [['started_at','ended_at'],['valid_from','valid_until'],['administered_at','next_due_at'],['performed_at','next_due_at']]){
  if(p[start]&&p[end]&&p[end]<p[start])throw new InputValidationError('تاریخ پایان نمی‌تواند پیش از تاریخ شروع باشد');
 }
 return p;
}
export function requiredValue(type,p){if(type==='condition'||type==='medication'||type==='procedure')return p.name;if(type==='allergy')return p.allergen;if(type==='vaccination')return p.vaccine_name;if(type==='task')return p.title;if(type==='insurance')return p.provider_name;if(type==='family_history')return p.relation&&p.condition_name;if(type==='screening')return p.screening_name;return true}
