import { supabase } from './_lib/db.js';
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function cleanHtml(html=''){return String(html).replace(/<(script|style|iframe|object|embed)[\s\S]*?<\/\1>/gi,'').replace(/\son\w+\s*=\s*(["']).*?\1/gi,'').replace(/javascript:/gi,'')}
function allowed(a){const verified=a?.doctor_profiles?.verification_status==='verified';return a?.status==='published'&&(verified||(a?.review_level==='editorial'&&a?.risk_level==='low'))}
function sourceItem(s){const title=typeof s==='string'?s:(s?.title||s?.url||'منبع');const url=typeof s==='object'?s?.url:null;return url&&/^https:\/\//i.test(url)?`<li><a href="${esc(url)}" rel="nofollow noopener" target="_blank">${esc(title)}</a></li>`:`<li>${esc(title)}</li>`}
const BASE=process.env.PUBLIC_SITE_URL||'https://drman.vercel.app';
function shell(title,desc,body,canonical,schema='',noindex=false){return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc||'مرکز دانش سلامت DrMan')}">${noindex?'<meta name="robots" content="noindex,nofollow">':''}<link rel="canonical" href="${esc(canonical)}">${schema?`<script type="application/ld+json">${schema}</script>`:''}<link rel="icon" type="image/png" href="/assets/drman-logo.png"><link href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@300;400;500;700;900&display=swap" rel="stylesheet"><style>:root{--bg:#050d1a;--s:#0a1628;--s2:#0f1e36;--a:#00d4ff;--g:#00ff9d;--y:#ffd060;--t:#e8f4ff;--d:#7aa0c4;--b:rgba(0,212,255,.15)}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--t);font-family:Vazirmatn,sans-serif;line-height:2}a{color:var(--a);text-decoration:none}header{padding:14px 22px;border-bottom:1px solid var(--b);display:flex;justify-content:space-between;gap:15px;align-items:center}.logo{font-weight:900;font-size:21px;display:flex;gap:8px;align-items:center}.logo img{width:38px;height:38px;border-radius:10px}.wrap{max-width:1050px;margin:auto;padding:38px 18px}.card{background:var(--s);border:1px solid var(--b);border-radius:20px;padding:25px;margin-bottom:15px}.muted{color:var(--d)}h1{line-height:1.45}.article h2,.article h3{margin-top:30px}.review{background:rgba(0,255,157,.06);border:1px solid rgba(0,255,157,.16);border-radius:13px;padding:12px}.editorial{background:rgba(255,208,96,.06);border-color:rgba(255,208,96,.2)}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.item{background:var(--s);border:1px solid var(--b);border-radius:16px;padding:18px}.item h2{font-size:18px;margin-top:0}.pill{display:inline-block;background:var(--s2);padding:2px 8px;border-radius:20px;font-size:11px;color:var(--d)}.filters{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.filters input,.filters select{background:var(--s2);border:1px solid var(--b);color:var(--t);padding:9px 10px;border-radius:10px;font:inherit}.filters button{background:linear-gradient(135deg,var(--a),#0870ff);border:0;color:white;padding:9px 14px;border-radius:10px;font:inherit}.sources{word-break:break-word}@media(max-width:650px){.grid{grid-template-columns:1fr}header nav{display:none}}</style></head><body><header><a class="logo" href="/"><img src="/assets/drman-logo.png" alt="DrMan">DrMan</a><nav><a href="/health">پرونده سلامت</a> · <a href="/learn">مرکز دانش</a></nav></header>${body}</body></html>`}
export default async function handler(req,res){
 if(req.method!=='GET')return res.status(405).end('Method not allowed');
 const slug=String(req.query?.slug||'').trim();res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','public, s-maxage=900, stale-while-revalidate=86400');
 if(!slug){
   const q=String(req.query?.q||'').trim().slice(0,80),category=String(req.query?.category||'').trim().slice(0,100);
   const {data}=await supabase.from('medical_articles').select('slug,title,summary,category,published_at,updated_at,featured,risk_level,review_level,author_name,doctor_profiles(full_name,specialty,slug,verification_status)').eq('status','published').order('featured',{ascending:false}).order('published_at',{ascending:false}).limit(300);
   let items=(data||[]).filter(allowed);
   const categories=[...new Set(items.map(x=>x.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fa'));
   if(category)items=items.filter(x=>x.category===category);
   if(q){const n=q.toLocaleLowerCase('fa');items=items.filter(x=>(x.title+' '+(x.summary||'')+' '+(x.category||'')).toLocaleLowerCase('fa').includes(n))}
   const cards=items.map(a=>{const reviewer=a.doctor_profiles?.verification_status==='verified'?('بازبینی پزشکی: '+a.doctor_profiles.full_name):'بازبینی تحریریه DrMan';return `<article class="item"><span class="pill">${esc(a.category||'سلامت')}</span><h2><a href="/learn/${encodeURIComponent(a.slug)}">${esc(a.title)}</a></h2><p class="muted">${esc(a.summary||'')}</p><small class="muted">${esc(reviewer)}</small></article>`}).join('');
   const filter=`<form class="filters" method="get" action="/learn"><input name="q" value="${esc(q)}" placeholder="جستجو در مقالات"><select name="category"><option value="">همه دسته‌ها</option>${categories.map(c=>`<option ${c===category?'selected':''} value="${esc(c)}">${esc(c)}</option>`).join('')}</select><button>جستجو</button></form>`;
   return res.status(200).send(shell('مرکز دانش سلامت | DrMan','مقالات و راهنماهای سلامت با منابع شفاف، بازبینی پزشکی برای موضوعات حساس و محتوای عمومی کم‌ریسک تحریریه DrMan.',`<main class="wrap"><section class="card"><h1>مرکز دانش سلامت</h1><p class="muted">راهنماهای قابل فهم درباره پرونده سلامت، آزمایش، سبک زندگی، مکمل‌ها، مراجعه و پیگیری. محتوای حساس پزشکی بدون پزشک بازبین منتشر نمی‌شود.</p>${filter}</section><section class="grid">${cards||'<div class="item muted">مطلبی با این فیلتر پیدا نشد.</div>'}</section></main>`,BASE+'/learn'));
 }
 const {data:a}=await supabase.from('medical_articles').select('slug,title,summary,body_html,category,keywords,seo_title,seo_description,source_links,published_at,updated_at,evidence_updated_at,next_review_at,ai_assisted,noindex,risk_level,review_level,author_name,status,doctor_profiles(full_name,specialty,slug,verification_status)').eq('slug',slug).eq('status','published').maybeSingle();
 if(!a||!allowed(a))return res.status(404).send(shell('مطلب پیدا نشد | DrMan','',`<main class="wrap"><div class="card">این مطلب در دسترس نیست.</div></main>`,BASE+'/learn','',true));
 const reviewer=a.doctor_profiles?.verification_status==='verified'?a.doctor_profiles:null;
 const authorName=a.author_name||'تحریریه DrMan';const reviewed=reviewer?`بازبینی پزشکی: <a href="/doctor/${encodeURIComponent(reviewer.slug)}">${esc(reviewer.full_name)}</a> — ${esc(reviewer.specialty)}`:`بازبینی تحریریه: ${esc(authorName)} · محتوای عمومی کم‌ریسک`;
 const schemaObj={'@context':'https://schema.org','@type':'MedicalWebPage',headline:a.title,description:a.seo_description||a.summary,datePublished:a.published_at,dateModified:a.updated_at,author:{'@type':'Organization',name:authorName},publisher:{'@type':'Organization',name:'DrMan',url:BASE},url:`${BASE}/learn/${a.slug}`};
 if(reviewer)schemaObj.reviewedBy={'@type':'Physician',name:reviewer.full_name,medicalSpecialty:reviewer.specialty,url:`${BASE}/doctor/${reviewer.slug}`};
 const schema=JSON.stringify(schemaObj).replace(/</g,'\\u003c');const sources=Array.isArray(a.source_links)?a.source_links:[];
 const meta=`<div class="review ${reviewer?'':'editorial'}">${reviewed}${a.ai_assisted?'<br><small>در تهیه پیش‌نویس از ابزار هوش مصنوعی استفاده شده و مسئولیت انتشار با بازبین است.</small>':''}${a.evidence_updated_at?`<br><small>آخرین بررسی منابع: ${esc(a.evidence_updated_at)}</small>`:''}</div>`;
 return res.status(200).send(shell(a.seo_title||`${a.title} | DrMan`,a.seo_description||a.summary||'',`<main class="wrap"><article class="card article"><span class="pill">${esc(a.category||'سلامت')}</span><h1>${esc(a.title)}</h1><p class="muted">${esc(a.summary||'')}</p>${meta}${cleanHtml(a.body_html)}${sources.length?`<h3>منابع</h3><ul class="sources">${sources.slice(0,20).map(sourceItem).join('')}</ul>`:''}<p class="muted">این مطلب آموزشی است و جایگزین تشخیص یا درمان فردی توسط پزشک نیست.</p></article></main>`,`${BASE}/learn/${a.slug}`,schema,a.noindex===true));
}
